:PROPERTIES:
#+TITLE: About Me
#+HERO: https://i.imgur.com/ALKlr6q.png
#+OPTIONS: html-style:nil
#+MACRO: imglnk @@html:<img src="$1">@@
#+OPTIONS: num:nil
:END:


* INTRO
:PROPERTIES:
:UNNUMBERED: notoc
:END:

I was born into a small town in Indiana in the year 2000. For the first 8
years of my life I was homeschooled so I could all over the world with
my parents. My parents decided that my sister and I needed more structured
learning, so in fourth grade I enrolled in the International School of Indiana.
There I developed my love of math, computing, and physics. After high school,
I enrolled in the Purdue University Honors Engineering program with ambitions
of becoming an aerospace engineer. I struggled to find meaning and clarity in
my studies throughout my first few years, switching majors a few times until
I landed on Economics, graduating with honors, a B.S. in Economics and a minor
in mathematics. The passion I developed in high school for computing returned
to me towards the end of college, and I picked up a job with [[https://counterpart.biz][Counterpart]] upon
graduating as a manager-developer hybrid. I live with my beautiful fiancée in
the San Francisco Bay Area.

* Other Interests

Aside from computing, there are many other subjects that still spark my interest
and passion.
