:PROPERTIES:
#+TITLE: Buddhism for Engineers
#+SUBTITLE: image by paul kidby
#+HERO: https://www.paulkidby.com/wp-content/uploads/2016/01/gallery_2-650x884_c.jpg
#+OPTIONS: html-style:nil
#+MACRO: imglnk @@html:<img src="$1">@@
#+OPTIONS: num:nil
:END:

* INTRO
:PROPERTIES:
:UNNUMBERED: notoc
:END:

I'm a professional software engineer, and I'm also someone who loves
going on meditation retreats. Most of my thoughts each day revolve
around the systems that I'm building, or around the life that I'm
living. For improving my skills in my work, reading and practicing
building software is the most helpful thing I can do. For improving my
skills in life, I've found practicing Buddhist teachings to be the
most helpful thing I can do. In this post I want to talk about
Buddhism as I understand it, and present it in a way that might make
sense to people used to thinking about building and designing systems
in STEM fields. Buddhism encompasses many ancient traditions of
carefully analyzing and systematizing experiential reality, here I
hope to make my contribution.

* Introducing Buddhism

Buddhist study primarily revolves around one thing: understanding the
teachings of Siddhartha Guatama (street name -> Buddha). Siddhartha
was believed to have been born nearly two and a half millenia ago
(~500 B.C.) to a royal family ruling a modest kingdom in northern
India. Legend says that one day Siddhartha escaped the palace grounds
and saw the surrounding city for the first time. He was appalled by
the squalor in which his subjects were living. He saw a sick man, an
old man, and a dead man. To the sheltered Siddhartha, this was his
first visceral encounter with three fundamental aspects of human
existence: sickness, old age, and death.

Upon returning to the palace Siddhartha's mind became fixated on
trying to resolve the anguish of this experience. How can we define a
sense of purpose in the face of forces so painful, yet so inescapable?
Later in life the legend says that he escaped from the palace by
nightfall on horseback. He set off in in search of a spiritual teacher
who could guide him towards enlightenment: an end to all stress,
worry, and suffering. After mastering the systems of various teachers,
but falling short of enlightenment, he set off by himself into the
wilderness.

In the wild he set his mind on completely desensitizing himself to all
suffering. Desensitization was to be achieved through harsh
asceticism, a form of torturing the body to build tolerance. He would
burn himself, starve himself, dehydrate himself, everything to push
his body and mind to the absolute brink. This also did not yield
enlightenment, causing him to leave a group of friends he had formed
to explore a new path.

This new path is something he would call "The Middle Way". It was a
system that focused on practitioners maintaining their health and
happiness in service of their practice. Instead of pushing and
torturing himself, he became dedicated to carefully watching his
mind. As he would sit and meditate, he would take breaks, and ensure
that this body was well fed and rested. On one fateful night, after a
few months of practice, he had a breakthrough. He saw the underlying
structure of his human condition. Before him crystallized the delusion
he had been stuck in, which had propelled the reapparance of
unhappiness, discomfort, and stress. In the final watch of the night
he finally understood how to be liberated of this illbeing, how to sit
in unshakable peace with reality. This state of peace is known in
Buddhism as nirvana (nibbāna). The word evokes the image of a candle's
flame being extinguished.

It's difficult to say with any certainty how many of the details of
his story are historically true. We can say with confidence that
Siddhartha was a real person, who grew an enormous monastic community
to practice his /Middle Way/. He spent most of the remainder of his
life wandering India, developing his monastic community, and
teaching.

Through comparative analysis, historians have been able to identify
collections of suttas (buddhist texts) that are considered
'early'. Though nothing the Buddha said was written down for more than
400 years after he passed away. Luckily, the teachings that we do have
form a remarkably cohesive and integrative philosophy and practice for
dealing with the challenges of life. Across the texts preserved in Sri
Lanka, to the sanskrit fragments preserved in mainland India, to the
texts preserved in China, we can confirm that the oral tradition which
transmitted Siddhartha's original teachings was remarkably
effective. These texts, which were written down separately based on
oral tradition, in separate regions, across separate centuries, share
a large corpus of texts which are nearly identical.

* Mechanics of Existence and Practice

The core of Siddhartha's teaching focuses on /dukkha/, how to
understand it, and how to follow a path which can lead to its
cessation. /Dukkha/ is a word that's difficult to translate to
English, but in the context of Buddhist practice implies a sense of
discomfort, troubledness, or pervasive stress. Siddhartha used this
word to refer to what he viewed as the fundamental, nearly
inescapable, human condition. He explained it in three levels of
depth:
1. Disease, old age, pain, stress, anxiety, and death are /dukkha/.
2. Pleasant things going away is /dukkha/, unpleasant things appearing
   is /dukkha/.
3. Everything is impermanent, nothing that is pleasant can last,
   therefore a permanent and lasting sense of satisfaction is
   impossible. The realization of the impermanence of all things is
   /dukkha/.

Understanding /dukkha/ is critical to understanding the mechanics of
our psychology. Why is the realization of impermanence /dukkha/? It
seems like a straightforward and obvious statement, there is nothing
that can escape change. The reality of impermanence creates tension
against the basic force in human psychology to subconsciously view
things as /permanent/. When we are happy, we are always happy about
something. If you buy a new car, there's going to be a sense of joy
and satisfaction when you drive it for the first time. However, that
pleasant experience will fade as the car ages, and will morph into a
frustration as you need to maintain it. That feeling of happiness is
/conditioned/ by the newness of the car, and is therefore bound to
that thing. The realization of impermanence is tied to realizing
that all happiness is bound to things which are fleeting. The first
danger to see when beginning Buddhist practice is becoming obsessed
with happiness which comes from unstable sources. Someone who can
source their happiness from their relationships will have a much
better life than someone who can only source their happiness from the
stock market.

In the face of impermanence, the way out is not to fall into nihilism,
or a strong rejection of (detachment from) the material world. It is
to use our understanding of the sources of /dukkha/ to build a
happier life. This forms the basis of one of the other major teachings
of the Buddha, the /Four Noble Truths/. They are simply explained as:
1. /Dukkha/ exists
2. /Dukkha/ is not random, but is conditioned, it has causes we can
   identify.
3. There is a practice hwhich can bring about the cessation of /dukkha/
4. This practice is the /Noble Eightfold Path/.

I won't go into detail specifically on the /Noble Eightfold Path/
here, but it is worth mentioning that it forms the hub of Siddhartha's
teachings. Nearly all of Siddhartha's teachings for how to practice,
how to live, how to think about the world, and how to meditate fall
into one of the spokes of the wheel of the eightfold path. The path
invites practitioners to develop right view, right resolve, right
speech, right conduct, right livelihood, right effort, right
mindfulness, and right /samadhi/. Unlike other systems, /right/ does
not correspond to a prescriptive set of rules to blindly follow, but a
set of principles the practitioner is invited to investigate and
develop confidence in. For the rest of this post, I would like to dive
deeper into right view, mindfulness, and samadhi.
