:PROPERTIES:
#+TITLE: Professional Work
#+HERO: https://i.imgur.com/Dc1baXQ.png
#+OPTIONS: html-style:nil
#+MACRO: imglnk @@html:<img src="$1">@@
#+OPTIONS: num:nil
:END:

* ScholarTrack

[[https://scholartrack.org][ScholarTrack]] is the primary platform for students in Indiana to apply for, and receive, financial
aid for Indiana universities and colleges. This platform was developed in-house by [[https://www.counterpart.biz][Counterpart]] for the Indiana Commission of
Higher education in 2017. I joined the Counterpart team in 2022 as project manager for the ScholarTrack
platform. I've worked with a team of excellent developers at Counterpart in implementing some landmark features,
like CHE's pre-admissions and auto-enrollment programs, which are set to give tens of thousands of students in Indiana
a leg up for getting into university. Each year our platform powers the distribution of [[https://www.in.gov/che/files/2022_College_Costs_Report_03_23_22b.pdf][hundreds of millions of dollars]]
of financial aid for students across Indiana.

* CHEDSS

CHEDSS is the internal data analysis tool used by the Indiana Commission of Higher education to help
them design policy around financial aid distribution. CHEDSS is used by the Indiana government, alongside
Indiana universities, to coordinate data collection, analyze trends, and take action on college
enrollment targets. I took over as technical lead for this project at [[https://www.counterpart.biz][Counterpart]] in 2022, where I spearheaded a
full redesign of their system.

* ngx-natlang

[[https://github.com/Sawyer-Powell/ngx-natlang][ngx-natlang]] is a collection of open source tools I worte, primarily for internal use at [[https://www.counterpart.biz][Counterpart]], to make it
simple to write AI powered experiences in Angular (and AngularJS for some of our legacy projects).
=ngx-natlang= builds upon the concept of AI =tools= and
extends it to the concept of =actions=, which are pieces of logic that deeply integrate into the frontend of
the application. Actions take structured input from the AI and feed that into a user defined functions. These functions
can make http requests, render custom components to an AI chat window, manipulate
arbitary frontend components, or even create custom dialog trees the user can have with the AI. =actions= offer a
convenient interface for programmers to exercise fine control over how a user interacts with an AI.

=ngx-natlang= is currently being deployed in various projects at [[https://www.counterpart.biz][Counterpart]].
