:PROPERTIES:
#+TITLE: New Stories to Reason Reality
#+SUBTITLE: image by paul kidby
#+HERO: https://www.paulkidby.com/wp-content/uploads/2016/01/Thud-1000x1335_c.jpg
#+OPTIONS: html-style:nil
#+MACRO: imglnk @@html:<img src="$1">@@
#+OPTIONS: num:nil
:END:

* INTRO
:PROPERTIES:
:UNNUMBERED: notoc
:END:

Reality is far stranger and far more incomprehensible than many of us
let on. It's easy to become confident about what is real, and what is
not. But this confidence is incredibly fragile. Mainly because we
become obsessed with a "factual" reality, one that we can point to and
describe, as opposed to a subtler reality that becomes availalble
through our awareness. Feelings of anxiety are driven by this
confusion. We have a belief about something that we hold as true, that
something is looming in the future. This worry drives an anxiety,
which is driven by this confidence about something that we believe
will happen. When you investigate with your awareness you realize that
the only real thing is the thought driving the anxiety, not the
looming consequence that you are obsessing over. The actual reality
touching the awareness is very simple, its the story woven by your
thoughts which drives a feeling of panic. Touch the reality of your
senses, there is an incredible amount of joy to be found there. And
the reality discovered through touching the senses is far more real
than the reality created through thinking.

Unpleasant feelings are real, they are there. But you can't do
anything about them. Just let them do their thing, get worse, get
better, anything is okay. This is the only thing that's important.

The thoughts don't paint picture of a real reality, they simply create
a compelling story that thoughts can get involved in again. When
you're body gets worried, anxious, etc, you're investing too much
energy into this fundamentally flawed story. There's no reason to keep
thinking about something which makes you stressed. There's no law of
reality that forces you to keep thinking about it. In fact, the more
you think about the thing that makes you stressed, the more trapped
you become. Just chill with the feelings, and realize that you aren't
going to solve anything with your thinking. Full stop.
